/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai;

/*import java.util.ArrayList;

import utils.*;
import utils.metrics.Metrics;*/

public class App {
    public static void main(String[] args){
    
    }
}
